name: Terraform Apply

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    inputs:
      approve:
        description: 'Approve Terraform changes'
        required: true
        default: false
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: echo "apply"
      
